### ISSUE TITLE
Auto-completion sometimes inserts wrong text

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#136]
My use case: add 1 to variables displayed.

## Before
```abl
MESSAGE "Range [" + STRING(iFrom) + ", " + STRING(iTo) + "]".
```

## Action
1. click between "STRING(iFrom" and ")"
2. hold CTRL key pressed to add a new caret
3. click between "STRING(iTo" and ")"
4. release CTRL and mouse button
5. insert 1 space
6. insert "+ 1"

## After
```abl
MESSAGE "Range [" + STRING(iFiTo + 1) + ", " + STRING(iTo + 1) + "]".
```

## What's wrong?
Have a look to "iFrom" changed to "iFiTo".

-----

Thanks for fixing.

Regards

**Comment by jcaillon** [comment]
When you pressed space, since the last caret was after iTo, the autocompletion "corrected" the case for iTo and modifed the text around your caret. But since you were in multi caret, it also changed the code near your first caret...
Fixed the autocompletion system to act only when the autocompletion popup is activated
