### ISSUE TITLE
Duplicated entries in auto-completion popup

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#138]
Have a look to this:
![1](https://cloud.githubusercontent.com/assets/7109720/20542218/f6f7be86-b100-11e6-9976-1e7fe4e64f6e.png)

Thanks for fixing this.
Reagrds,
C.CLEAUD

**Comment by jcaillon** [comment]
It actually makes sense. Since the appbuilder creates a new `&scoped-define` variable for each `ON` statement but never `&undefine` it...

Check out your .w file, you will see a lot of :
`&Scoped-define SELF-NAME xxx`
But not a single 
`&undefine`

If you display the tooltip for each of your `&SELF-NAME` you will see that they have different values -> hence they are different, this would not make more sense to only display one (which one would we display then??)
