### ISSUE TITLE
how to get a .pf file

### ISSUE THREAD

**Issue by devjerome** [jcaillon/3P#142]

**Comment by ccleaud** [comment]
Hi @devjerome ,
Did you think this is linked to #94 or do you use another use-case?
Thanks

**Comment by jcaillon** [comment]
Hello, this issue is not related to 3P but to the usage of Progress itself.
Please understand that the main goal of the "issues" section on github is to discuss issues concerning the prject itself. 

However, I invite you to read the following documentation concerning your request : 

[https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvdbt/creating-a-parameter-file.html](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvdbt/creating-a-parameter-file.html)
