### ISSUE TITLE
Incremental search field looses focus

### ISSUE THREAD

**Issue by wbarman** [jcaillon/3P#157]
Incremental search text field looses focus after every key stroke, so it's unusable.
How to recreate the issue:
- open any .p file (or .i, .cls)
- press Ctrl + Alt + I (Incremental Search) - search text field has focus now
- start typing - search field losses focus after first hit; main editor windows has the focus

But it works fine for regular .txt files.

**Comment by jcaillon** [comment]
Hi,

Thanks, I've indeed reproduced the issue in the latest stable version (v1.7.0). 
However this is fixed in the next beta version (v1.7.4) :)

Thank you for reporting the issue, you can either wait for the next stable release or the next beta release.
Your 3P will be updated automatically if you go to options > updates > I want the beta releases
