### ISSUE TITLE
Enhancement Idea: Remote Management

### ISSUE THREAD

**Issue by ray73864** [jcaillon/3P#169]
One thing that the AppBuilder does which I have to use for work (Hate the appbuilder, it has so many annoying issues) is the 'Remote Management' mode, when you click the little computer icon in the toolbar it switches to a gear and the 'File->Open' switches from local to remote mode.

This allows one to remotely edit files that are on the defined server and then when you click on 'save' it saves it back to the server and compiles it on the server at the same time.

**Comment by jcaillon** [comment]
Hello,

Since i'm integrated within notepad++, id rather let notepad handle opening files.
This is less accessible than the appbuilder, but you can already reproduce the remote management with the current version of 3P.
You will need an extra notepad plugin which is nppFTP (already installed by default) -> it allows to connect to a remote location and edit your files within notepad; they are uploaded on save.
Next, you will need to be able to compile directly to the remote server. You can do that easily by using a deployment transfer rule of type FTP (see http://jcaillon.github.io/3P/#/deployment). Then, when you compile your program, the rcode will automatically be uploaded to the remote location of your choice.

br
