### ISSUE TITLE
Syntax highlight issue

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#185]
Hi,
I found an issue again... I use my own syntax highlight schema (user define language). And I use standart DeepBlack color theme.
I turned off checkbox Option > Color Schema > Syntax highlight.
When I open any progress file my schema isn't applied :(
https://i.imgur.com/6BfeRU7.png

I do not have such issue on v1.7.4

NP 7.51 x64, 3P v1.7.6

**Comment by jcaillon** [comment]
Hello,

Since 1.7.6 3P does not use UDL anymore. I doubt a UDL can be as good as a custom lexer and this will become even more true when I start coloring stuff dynamically (like variables, methods, function and so on...).

You should consider using the default syntax highlighter instead of your own now. please tell me if something is missing in mine. Also, if it is only a matter of color, you can fully customize the syntax color in 3P -> [https://jcaillon.github.io/3P/#/custom-themes](https://jcaillon.github.io/3P/#/custom-themes). Please make your own scheme and submit it to share it with the community :)

I should already have removed the checkbox you are talking about as it is now irrelevant, ill delete it in the next version.

Regards

**Comment by TestUser013** [comment]
Thanks, I will manage with it as soon as get free time :)
