### ISSUE TITLE
Support for ISO8859-15

### ISSUE THREAD

**Issue by baltazaroliveira** [jcaillon/3P#188]
### Description of the Issue

Don´t have support for ISO8859-15

### Steps to Reproduce the Issue

Ok

![image](https://user-images.githubusercontent.com/953742/33216670-bf64734a-d12c-11e7-9f3a-9b165681df66.png)

In the program, NOK

![image](https://user-images.githubusercontent.com/953742/33216687-d22cd544-d12c-11e7-809d-8db43ec20e51.png)

### Expected Behavior
The symbol € should appear

### Actual Behavior
The symbol € is replaced by another...

**Comment by jcaillon** [comment]
Hello,

This issue is not related to 3P but to notepad++. Check the encoding currently in use in the bottom status bar of notepad ++ : 

![image](https://user-images.githubusercontent.com/11553075/33217295-9bece27a-d137-11e7-8104-e443c52f61a8.png)

If it is not the encoding you want, you can reload your file with a given encoding in notepad++ by doing : 

![image](https://user-images.githubusercontent.com/11553075/33217265-7c19af8c-d137-11e7-9f2d-e16b238cfcb2.png)

Notepad++ just loaded your file with another encoding.

**Comment by baltazaroliveira** [comment]
Doing that, the symbols don´t appear Ok..

![image](https://user-images.githubusercontent.com/953742/33323217-aabd2242-d443-11e7-83da-8791d66e273b.png)

**Comment by jcaillon** [comment]
I said ISO 8859-15 because it is what is written in your comment. If other characters don't appear right with this encoding then *your comment (in the code) is wrong*. You need to use the charset that has both the EURO symbol and what i assume are Portuguese accents. I quick google search suggests you should use ISO 8859-1 encoding under Western European in notepad++.
See this page... http://scratchpad.wikia.com/wiki/Character_Encoding_Recommendation_for_Languages

You might also want to check $DLC/startup.pf and see the encoding used for -cpstream or cpinternal.

Again, absolutely nothing to do with 3P :)

**Comment by baltazaroliveira** [comment]
My encoding is not wrong. Works perfectly on ProcedureEditor.

My .pf is this

![image](https://user-images.githubusercontent.com/953742/33931786-0244b006-dfe9-11e7-8e96-b04963cc64af.png)

Maybe Notepad++ doen´st support it.

I will use the native. Thanks!
