### ISSUE TITLE
Code Explorer : Refresh tree now is too long

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#198]
Version 1.7.7

If I switch to another file refresh of my tree in Code Explorer now is 10-15 sec

![default](https://user-images.githubusercontent.com/35800954/35389225-93728a04-01df-11e8-9cfd-8161de059907.png)

It worked fine in previous version

**Comment by jcaillon** [comment]
Hello,

Can you please provide details on this issue? It doesn't happen on my end so i will have a hard time figuring out what causes the slow down.

- Between which type of files does the slow down occur (only progress files?)? 
- Are those big files (>100Mo for instance?) 
- Do you have problems switching between openedge files only? Or does it happen also between other type of files? 
- Do you have a custom UDL for openedge in notepad++?
- If it only happens on certain progress programs, do they contain a lot of {includes} or a lot of pre-processed variable {&var}?

**Comment by gudzelayk** [comment]
Switching only between .p files(size if up to 1MB)
Custom UDL is deleted so a little bit faster now 
If I have 10+ includes switching is much slower

I'm guessing it is as I have a lot of big includes

**Comment by jcaillon** [comment]
Please also answer the last question regarding include files.
The red barrier icon signifies that the file was not found in your propath or in your source folder. If you have a lot of files in your source path/propath this can cause the parser to slow down because it has to try to find this files in your hdd (which is a very slow operation).
If you have the red barrier, correct your propath so the include can be found.

**Comment by jcaillon** [comment]
Hi, did you see my previous question?

**Comment by gudzelayk** [comment]
Hi, If file has a lot if includes it takes some time. If up to 10 more-less quick
All includes are in my propath so no issues here
