### ISSUE TITLE
Enhancement DB Table pop-up info

### ISSUE THREAD

**Issue by gudzelayk** [jcaillon/3P#199]
Could you please move help info at the top 

![default](https://user-images.githubusercontent.com/35800954/35389896-176accac-01e2-11e8-92f0-2dd2aba52bb1.png)

Is it possible show order of fields like:

- Fields from Primary Index
- Other fields

Now it is shown by order I guess

**Comment by jcaillon** [comment]
It is currently shown in the order of definition in the database yes. Sure i can sort them.

For the help info at the top, this is not possible as you show it because there is another information at this position. But I imagine that you want it on top to see it even  when the tooltip needs to be scrolled?

![image](https://user-images.githubusercontent.com/11553075/35615393-4f6a25b4-0672-11e8-868e-cf56b385afc3.png)

Ill look for another solution

**Comment by jcaillon** [comment]
![image](https://user-images.githubusercontent.com/11553075/36098227-751fcf76-0ffe-11e8-9895-1c98e4d1f37a.png)

**Comment by gudzelayk** [comment]
Perfect!
