### ISSUE TITLE
Code commenting / uncommenting does not really work

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#21]
Hi,

Just for the fun, a new bug report.
1. open a Progress ABL source file (expected : at least 300 lines of code but it failed on even 10 in some circumstances)
2. select all text (CTRL+A)
3. press CTRL+Q
4. do NOT release CTRL+Q
5. wait for 10 seconds

**Comment by ccleaud** [comment]
Not that easy to reproduce.
You can open a file, and select 1 word then play with CTRL+Q and see strange behaviors:
1. other lins are commented
2. text selection moves to the end of document

**Comment by ccleaud** [comment]
You're welcome to ask me to reproduce.

**Comment by jcaillon** [comment]
**Ok**,

I couldn't reproduce your bug once again, holding CTRL+Q after selecting all the text in a 44k lines document doesn't crash notepad++. However, the function runs slowly as it has to comment each 44k lines one by one....

The toggle comment feature now works differently :
 * if there is not selection, toggle on/off the current line
 * if there is a selection, toggle on/off the selected BLOCK
 * Now also works for multiple selections

I also added module to prevent the user from spamming a key.

Since i completely refactored the function, i'll consider this bug corrected.

Corrections included in v1.0.1

**Comment by ccleaud** [comment]
Let's talk about this trouble next tuesday morning while drinking coffee ^^

**Comment by ccleaud** [comment]
Please note it doesn't crash Notepad++, it only have trouble with text selection thant causes more than selected lines to be commented / uncommented.

**Comment by jcaillon** [comment]
Oh, ok i see what you mean; Yeah the selection was wrongly expanded after adding `/*` and `*/`, this is fixed now
