### ISSUE TITLE
Formatting changes to italics

### ISSUE THREAD

**Issue by APenguini** [jcaillon/3P#223]
### Description of the Issue

At random times when scrolling through a file the text formatting flips to all blue italics.  Sometimes changing to another 3P/ABL file and back will cause the formatting to correct itself. Sometimes typing a space and save and it will correct. Other times it just stays blue italics.

### Steps to Reproduce the Issue

1. Scrolling down through a large file text flips from OE ABL formatting to blue italics.  

### Expected Behavior

Text remains formatted as defined by 3p

### Actual Behavior

Text flips to blue italics. (See first screenshot)

### Debug Information

3P version 1.7.7
npp version 7.5.6
No other ABL language definitions (See last screenshot)

npp debug info:

```
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : 3P.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll 

```

**Blue Italics at bottom**
![image](https://user-images.githubusercontent.com/8633289/38328784-c938b03a-3819-11e8-82a3-6e0eb8a07a84.png)

**No user defined languages**
![image](https://user-images.githubusercontent.com/8633289/38328776-c4ca2772-3819-11e8-90bc-2fd6ba46f1ab.png)

**Comment by jcaillon** [comment]
Hi,

Never seen this behavior, I have around 10 people using 3P daily on atrociously large files and none reported that kind of bug. 

I see 2 likely causes : 
- It comes from notepad++ (somehow? but unlikely) -> we are all using a slightly lower version of npp v7.5.4
- it comes from another plugin -> altough i see you don't have a lot of these (thank you for all the details on the issue btw!)

I'm pretty confident that it doesn't come from 3P because, at worse, the text would just not be colorized. But it being blue and italic is weird. 

Can you do the following test? 
- get minimal npp version v7.5.4 : https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.minimalist.7z
- install the latest 3P version v1.8.1 : https://github.com/jcaillon/3P/releases/download/v1.8.1/3P.zip

Try this configuration without extra plugins for a day and see if it is better? 


Just for the sake of completeness, can you tell me what is the current language selected by notepad++? bottom left corner : 
 
![image](https://user-images.githubusercontent.com/11553075/38330924-28c71b30-3852-11e8-98b2-9bf11302839e.png)

**Comment by APenguini** [comment]
First thank you again! 3P is a great tool, I'm getting a lot of use out of it.

It is Normal Text for the language. And that does not change when the text changes to italics. As stated, the italics change happens when I scroll down (using my mouse wheel btw, although that shouldn't matter.) It just happened again this morning and I noticed that the language (Normal text) did not change.  I will try the above suggestions and let you know.

As for plugins, one that may be not playing nice with 3P is the compare plugin. I have also noticed on multiple occasions when I use the compare plugin that I get very strange colored text on the right-hand comparison. Again, not all of the time so I don't have a current screenshot but if I see it again and you think it would help I'll send that as well.

**Comment by APenguini** [comment]
This is still happening on a regular basis. 3P is great so I really want to use it and this behavior makes that harder to do. I've attached a screenshot below of the other plugins I have. Would you mind letting me know any that you and others are NOT using.  I'll try removing them all and adding them back one by one to see which one is causing my issue (if in fact its another plugin.)  If there's any other info that may help you troubleshoot let me know.  And thanks again. Really nice addition.

![image](https://user-images.githubusercontent.com/8633289/39495041-9f84e17a-4d66-11e8-89fe-b18b9c0d0101.png)

**Comment by APenguini** [comment]
I took out the two you mention above and it happened again. See image below. However, could you check to see if perhaps the "editing:" keyword/label could be the issue?  So far the files I see it happen in are fairly large with editing phrases.  Old QAD code so that's how it works :-/  

Anyway, I changed the editing: to a do:  in one of them and although that breaks my code, the formatting looks right now. Thanks.

![image](https://user-images.githubusercontent.com/8633289/39545290-b6d9a578-4e1e-11e8-92f4-8144d4415742.png)

**Comment by jcaillon** [comment]
Do you have a file with which you can constantly reproduce the issue?
If so, would you be willing to send it to me?

The problem can't be related to be a parser error, i don't see how the use of the editing keyword would have any impact. Moreover, it works for anyone else :/ This problem is, im afraid, localized to your specific environment/code.

If i were you, i would really try to start from a fresh minimal and local installation of notepad++, install only 3P and see how this goes (as stated in my second comment). You can easily copy your 3P configuration to your fresh install (copy the 3P directory from the old location %notepad++install_directory%/plugins/config/3P to your new location).

![image](https://user-images.githubusercontent.com/11553075/39575887-6d798286-4edc-11e8-9afa-dc63144eea1f.png)
