### ISSUE TITLE
Lighten loading time [CHALLENGE] [ENHANCEMENT]

### ISSUE THREAD

**Issue by ccleaud** [jcaillon/3P#24]
Hi,

Is there a way to lighten the loading time of the plugin?

On a quite recent computer, N++ takes 1 to 2 more seconds to get ready when the plugin is installed.
Is there a way to split the plugin into 2 DLL, one acting as a stub providing every things requested by (N++ <-> plugin) interface and another containing the intelligence?
The other would load with a small delay...

Do you think this is possible?

Thanks,
Regards,
C.CLEAUD

**Comment by jcaillon** [comment]
Done in the next release,

The loading time has been decreased dramatically, it takes about 150ms on my computer

**Comment by jcaillon** [comment]
I actually had to rollback this modification, this was creating random (really fucking random) issues; i struggled for a few hours before giving up, i'll try later.
The loading is still improved quite a bit because i got rid of stuff on startup.
Btw, what i previously only consisted in moving some of the startup computation asynchronously, splitting up the dll might be the next step. But for now, it's easier to handle a single .dll, ill externalize stuff when i come with an easier installer.

**Comment by jcaillon** [comment]
3P increases the loading time of Notepad++ -> that's a fact.
However, since the version 1.2.1, most of the time consuming process are done on background threads so the startup is now fast enough IMO.
