### ISSUE TITLE
Admin rights required to update 3P for notepad++ version 7.6.1 to 7.6.2

### ISSUE THREAD

**Issue by gurikbal** [jcaillon/3P#249]
![capture-20190125-202057](https://user-images.githubusercontent.com/36083297/51783725-39b32a00-2164-11e9-9569-f595e1aefa58.png)
![capture-20190125-202241](https://user-images.githubusercontent.com/36083297/51783728-3e77de00-2164-11e9-9379-ad17e55b3aa2.png)
Description of the Issue

after auto update 3p plugin give error messeges

[i accept there plugin directory are changed in Notepad++ v7.6.1 and will be next version changes too](https://notepad-plus-plus.org/community/topic/16996/new-plugins-home-round-2)

Debug Information
Notepad++ v7.6.1 (32-bit)
Build time : Dec 12 2018 - 01:24:22
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : 3P.dll Console_output.dll DSpellCheck.dll mimeTools.dll NppConsole.dll NppConverter.dll NppFTP.dll NppToolBucket.dll PythonScript.dll Remove_dup_lines.dll

**Comment by jcaillon** [comment]
Hello, is it possible that you had several instances of notepad++ started?
Did you have a popup asking you to run 3pUpdater with admin rights when you closed notepad++?

**Comment by gurikbal** [comment]
[Presentation1.pptx](https://github.com/jcaillon/3P/files/2824633/Presentation1.pptx)

**Comment by jcaillon** [comment]
Sorry, I can't open a random 20Mb .pptx from the internet x)
If you are not going to use github comments, please use a safer file format (.pdf?).

**Comment by gurikbal** [comment]
[.pptx was contain a video file you can wacth it at youtube](https://www.youtube.com/watch?v=UlQgtss32YE)

**Comment by jcaillon** [comment]
Alright! Thank you for the video, it helped me understand the issue :)

I just reproduced with notepad++ v7.6.1 (it works fine for the latest version which is v7.6.3).

There has been a lot of changes regarding the location of plugins in v7.6.x:

- in v7.6.0, plugins were moved from /plugins/PLUGINNAME.dll to /plugins/PLUGINNAME/PLUGINNAME.dll
- in v7.6.1, the base plugins folder was moved from %LOCALAPPDATA% to %PROGRAMDATA%
- in v7.6.3, the base plugins folder is now always `%ProgramFiles%\Notepad++\plugins\` (for non portable installation)

The problem you encounter is only for v7.6.1 because the 3P.dll is copied with admin rights in %PROGRAMDATA% and I do not correctly detect the need for admin rights to override the file during a 3P update...

The easiest fix is to reinstall v7.6.3. I'll try to handle this particular case, but since it only happens in v7.6.1 and v7.6.2, it should not impact a lot of users.
