### ISSUE TITLE
Auto-completion issue!

### ISSUE THREAD

**Issue by raziEiL** [jcaillon/3P#262]
Auto-completion stopped working after NPP update. CTRL+TAB keys open words list but do not direct to word. NPP vanilla auto-completion feature works fine.

![notepad++_5bhBqsfORo](https://user-images.githubusercontent.com/2551987/59560736-1b28cf00-9030-11e9-95b8-8d5134180ffa.jpg)

```Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : 3P.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExec.dll 
```

**Comment by jcaillon** [comment]
Hi,

Did you happen to update NPP to version 7.7?

A new version of scintilla (the text editor component of npp) has been packed with version 7.7 and it is causing issues with many plugins. 3p is unfortunately no exception since it interacts a lot with scintilla.

Until the next release of 3P, your only option will be to stick with version 7.6.6.

If you are not in version 7.7, let me know and I will look further into it.

Best regards

**Comment by jcaillon** [comment]
Just noticed the build time is matching v7.7 so I guess this is indeed the issue.

Closing this issue, you can follow #263

Have a great day

**Comment by raziEiL** [comment]
> Hi,
> 
> Did you happen to update NPP to version 7.7?
> 
> A new version of scintilla (the text editor component of npp) has been packed with version 7.7 and it is causing issues with many plugins. 3p is unfortunately no exception since it interacts a lot with scintilla.
> 
> Until the next release of 3P, your only option will be to stick with version 7.6.6.
> 
> If you are not in version 7.7, let me know and I will look further into it.
> 
> Best regards

Yes, it happened in 7.7. Well, I'm waiting for 3p updates and rolled back to 7.6. Good luck and have a great day too!
