### ISSUE TITLE
On run window appears and then disappears

### ISSUE THREAD

**Issue by DakotaMcCutch** [jcaillon/3P#291]
I don't know if this is a bug or I am missing a configuration setting or not.

But when I execute a .p file that has a display command on it, the window appears like it would when run in app builder, but then it doesn't seem to display and things then instantly disappear again.

**Comment by jcaillon** [comment]
Expected behavior.

DISPLAY is used for console interface. Use MESSAGE to display debug messages instead.
You can also use the other progress program instead of prowin to display the console (i don't recall its name, something like _progres.exe). IIRC you also need to wait for user input at some point if you do not want your program to immediatly end and thus only displaying briefly your messages.

3P is only executing a program and passing some arguments. It is up to you to configure it so it does what you want. I did not program in progress for 4 years now so I forgot a lot of stuff and can't really help you on that.

If that helps, I have a recap (comments in french, do a google trad) of ABL language here: https://github.com/jcaillon/Notes/blob/master/openedge/recap.p
