### ISSUE TITLE
Syntax case and autocomplete running inside comments

### ISSUE THREAD

**Issue by kger** [jcaillon/3P#293]
Is there a way to stop this?  

I turned off the setting to force the autocomplete when starting a new word, and that helps.  (The autocomplete options list appears, but no longer does 3P force the first match when I hit the space bar.)  However, the syntax case is still being forced inside comments.  This happens within both styles of comments.

**Comment by jcaillon** [comment]
This should not happen and there is already an option (disabled by default for this):

![image](https://user-images.githubusercontent.com/11553075/171444904-f0ac22cd-77c7-4083-9aec-1a3386796f95.png)

What version of notepad++ are you using?

I just tried 3P on the latest version and I do not have the syntax lightning... I think it stopped working from notepad++ version 8. They must have changed something in the API.

Download this version https://notepad-plus-plus.org/downloads/v7.9.5/, install 3P again and you should see syntax highlighting:

![image](https://user-images.githubusercontent.com/11553075/171445567-c0fd8d7e-0235-4a0c-962b-97e542a2d027.png)

Then it will behave as you expect because it detects that you are in a comment.

**Comment by HanzieV** [comment]
Hi, downgrading to version 7.9.5 is not an option for me as my organization forces updating to N++ to 8.4.  Any other solution for this ?

**Comment by jcaillon** [comment]
Fixxed
