### ISSUE TITLE
Feedback users

### ISSUE THREAD

**Issue by jcaillon** [jcaillon/3P#3]
# What's the point of this issue? #

3P users's can submit feedback about the application, suggesting new features or just let me know i'm on the right tracks.

**Comment by nashokkumarbabu** [comment]
Hi 
Happy to see the editor for the 4gl editor. Thank you.
We have one feature requirement  development environment for our system is unix environment where and we develop on windows and upload using editplus feature can we have similar functionality in file explorer ?

Thank you
Ashok

**Comment by jcaillon** [comment]
Hello Ashok,

Sorry for the late answer, I just saw your message! 

As a matter of fact, the next release should include FTP transfers capability under the **deploy your application** feature. I think this will answer your needs. I will write back here when the release is done to let you know how you can configure 3P to do what you want.

In the meantime, could you tell me if you are using FTP/FTPs or STFP?

**Comment by jcaillon** [comment]
Hi Ashok,

As promised, here is the page describing how to achieve this feature : 
[http://jcaillon.github.io/3P/#/deployment-usage-examples](http://jcaillon.github.io/3P/#/deployment-usage-examples)

A real integration in the file explorer (as you asked) will probably come later!

**Comment by EduardoHFreitas** [comment]
Hello Julien,

I'm using the editor and it really is very good. But I meet the same problem that Ashok ...

I am using a Unix server and need an integration to grab the sources of every directory of my PROPATH, the tool already contains this integration?

And you have some tutorial for developing character mode (using the _progres.exe instead of prowin.exe)?

Already, thank you!

Att, Eduardo.

**Comment by jcaillon** [comment]
Hello Eduardo,

I'm sure if I understand what you need correctly :
- do you need to send all your source files (*.w, *.p, *.i) to a distant server automatically? (if so, yes the tool does it)
- do you need to first compile all the sources and send the *.r code to the distant server? (if so, the tool does it too)
- or do you need to download source files from a distant server into your computer? In that case it doesn't do it but I don't see the point?

As for your second question : if you only have programs in character mode, you can simply replace the path to `prowin32.exe` by the path to `_progres.exe`, it will work just as fine.

**Comment by EduardoHFreitas** [comment]
Hello Julien,

Sorry, maybe I have not expressed myself right.

I work with my sources on a remote server, divided into a hierarchy of directories. I needed that, instead of having my sources in a local folder, I could list my sources on the server and can navigate between directories. A sync with the server similar to the operation of NppFTP.

And about the compilation, we use the RunTime version of Progres. Is there any way to run the source on the server or locally without compile them?

Already, thank you!

**Comment by jcaillon** [comment]
Hello,

Ok I see; the thing is, 3P was designed to work with developper version of Progress installed on the computer. This is the only that you can check the syntax/compile your sources as well as explore your database and extract its structure to autocomplete tables/fields. You have access to a very limited panel of 3P features if you are bound to the run time version :/

To answer your question, there is nothing in 3P that allows you to work with the sources on a remote server (again, in my logic, you are supposed to have the developper version and your sources on your computer). Also, with the runtime version, you have no choice but to compile your sources on the server and then execute the *.r code on your computer.

Sorry to not be able to help you more than this :/

**Comment by patrickTingen** [comment]
Hi Julien, good to read you integrate the [DataDigger](https://datadigger.wordpress.com/) straight from GitHub instead of packing it as a part of 3P. Good choice!

**Comment by DakotaMcCutch** [comment]
A suggestion is is there a way to set the file explorer so it does open with all the folders expanded. Some of the directories have a lot in them and it opens with them expanded. I prefer if they were collapsed for sanity reasons. Its  not a huge thing since I can just hit the collapse but to make them collapse just thought would suggest an option
