### ISSUE TITLE
Custom syntax highlighting.

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#66]
Hi, 
NP++ always use syntax highlighting selected in the menu 3P->Option->Color Schemes->Syntax Highlighting (Default, Tomorrow or Michael Knight).

NP++ doesn't use the styles that are specified in userDefineLang.xml. I have changed settings (color and style) in Language->Define your language->OpenEdgeABL. My changes don't apply automatically when I open file (or restart NP++) . They are applied when I select OpenEdgeABL in language menu by myself.

And one more issue. NP++ doesn't apply user define language using file extension. I delete file extension list for user define language OpenEdgeABL and add file extension list to my own user define language. NP++ uses syntax highlighting selected in the menu 3P after this change.

Can you fix, please? Thanks a lot.

PS: 3P->Option->Updates->Do not install syntax highlighting on update set as ON.

**Comment by jcaillon** [comment]
Hi,

Thank you for reporting this! Indeed, 3P currently forces the colors of the syntax highlighting each time the user changes the current document! This is why your settings are only applied when your select the language manually. 
-> I will add the option to not use the color scheme for the syntax highlighting

As for your second remark; it works on my end! 
1. Delete the file extension associated with OpenEdgeAbl :
![image](https://cloud.githubusercontent.com/assets/11553075/13570508/eb7d0502-e46e-11e5-8471-27d3243ba1de.png)
2. Create a new user defined language, set the associated extensions to `p i t w cls lst` :
![image](https://cloud.githubusercontent.com/assets/11553075/13570546/2a85547a-e46f-11e5-98b2-72d9b18ce2cb.png)
3. The new defined language will now be used for the selected extensions.

Be careful tho, you need to close/re-open your files or manually select which user defined language to use before you see the changes! This is a problem related to notepad++ not 3P though :)

However, since 3P forces the color scheme each time you open/switch document, you will be unable to change the colors of the user defined language for now...

**Comment by TestUser013** [comment]
> -> I will add the option to not use the color scheme for the syntax highlighting
Thanks a lot, I''ll waiting this option :+1:  :)

**Comment by jcaillon** [comment]
Hello,

I've done the modification, it will be applied at the next beta release (1.4.1). It should be available within a week :)

Here is the option : 
![image](https://cloud.githubusercontent.com/assets/11553075/13789743/b482d202-eae5-11e5-9296-e549ead81352.png)

I will close the issue once I do the release, so you can know when it is available

**Comment by jcaillon** [comment]
Hi,

A new release is available! I've added an option that should interest you, please let me know if you find it handy! It allows you to easily customize the colors and font weight of each type of keywords through a plain text file.

**Comment by TestUser013** [comment]
Thanks, it's very useful for me :+1
