### ISSUE TITLE
Don`t work auto-case mod :(

### ISSUE THREAD

**Issue by TestUser013** [jcaillon/3P#69]
Hi,
I downloaded version 1.5 and I tried change auto-case mod to lowercased (2) as you can see at screenshot http://i.imgur.com/RlD6wI6.png

But than I started type standard word and used auto-completion and pressed {Enter} or {Tab} - i got uppercase word. 
http://i.imgur.com/DoxGm68.png

As i remember it's work fine in older versions :)

**Comment by jcaillon** [comment]
Hello,

You probably dit it, but once you entered the new value of the mode (i.e. 2), you need to click on the save button in order to apply your changes.
![save](https://cloud.githubusercontent.com/assets/11553075/15015419/0aaaf98c-120c-11e6-922e-aeae669b1327.png)

However you are right, if you type a word and press TAB or ENTER you do get the word in uppercase, **the case is only corrected once you insert a space or a point and so on**... If you naturally write code this shouldn't bother you, but if you only want to autocomplete a word this can be annoying.

I'll make sure to correct the case when the word is autocompleted (instead of waiting for the next character) in the next version.

Ty for your feedback :)

**Comment by jcaillon** [comment]
Corrected with the commit :
https://github.com/jcaillon/3P/commit/79ee93c5734a7609b8db32afdb46ed48c4dc1e53

It should be live with the next beta release 1.5.2!
