### ISSUE TITLE
Files With No Extensions

### ISSUE THREAD

**Issue by odin-vii** [jcaillon/3P#80]
I support an old system that for some reason decided having no file extensions on any of the files was a good idea. We've moved away from that model, but the vast majority of the code in our system still has no file extensions. Is there anyway to have these files activate the 3P features?

**Comment by jcaillon** [comment]
Hi,

Sorry for the late answer, I was on holidays!
Obviously, this is not supported by v1.7.0, I didn't imagine that such case would happen. I can (and actually I was already planning to) modify the extension matching system so it uses wildcards (* and ?) :
![image](https://cloud.githubusercontent.com/assets/11553075/17824094/407a26ac-6660-11e6-9eaa-7cf6b86e3df5.png)
With this, you will be able to input only `*` and this will match all the files (the downside is, EVERY file will be seen as progress files by 3P).
The problem is, the current syntax highlighter is based of the User Defined Language (shipped with notepad++) and there are no way to specify "no extensions". So you will have to manually select the language in notepad++ : Language > OpenEdgeAbl.

**Comment by odin-vii** [comment]
That would be a huge help. Most tools we've been looking at have had a similar issue, including the studio provided by Progress.

**Comment by jcaillon** [comment]
done for the version 1.7.1
